"""Shared provider types for the merge queue.

GitHubClientProtocol defines the interface that all providers must implement.
RateLimitInfo tracks GitHub API rate limit state.
"""

from __future__ import annotations

import datetime
import logging
from typing import Any, Protocol

import requests

log = logging.getLogger(__name__)


class RateLimitInfo:
    """Tracks GitHub API rate limit state from response headers."""

    def __init__(self) -> None:
        self.limit: int = 0
        self.remaining: int = 0
        self.used: int = 0
        self.reset_at: datetime.datetime | None = None
        self.request_count: int = 0

    def update(self, response: requests.Response) -> None:
        self.request_count += 1
        headers = response.headers
        if "X-RateLimit-Limit" in headers:
            self.limit = int(headers["X-RateLimit-Limit"])
        if "X-RateLimit-Remaining" in headers:
            self.remaining = int(headers["X-RateLimit-Remaining"])
        if "X-RateLimit-Used" in headers:
            self.used = int(headers["X-RateLimit-Used"])
        if "X-RateLimit-Reset" in headers:
            self.reset_at = datetime.datetime.fromtimestamp(
                int(headers["X-RateLimit-Reset"]), tz=datetime.timezone.utc
            )

        if self.remaining > 0 and self.remaining <= 100:
            log.warning(
                "GitHub API rate limit low: %d/%d remaining (resets %s)",
                self.remaining,
                self.limit,
                self.reset_at,
            )

    def summary(self) -> str:
        return (
            f"requests={self.request_count}, "
            f"remaining={self.remaining}/{self.limit}, "
            f"resets={self.reset_at}"
        )


class GitHubClientProtocol(Protocol):
    """Protocol for testing — mock this instead of the concrete class."""

    def list_open_prs(self) -> list[dict[str, Any]]: ...
    def get_label_timestamp(
        self, pr_number: int, label: str
    ) -> datetime.datetime | None: ...
    def add_label(self, pr_number: int, label: str) -> None: ...
    def remove_label(self, pr_number: int, label: str) -> None: ...
    def create_comment(self, pr_number: int, body: str) -> int: ...
    def update_comment(self, comment_id: int, body: str) -> None: ...
    def get_failed_job_info(self, run_url: str) -> tuple[str, str]: ...
    def create_ruleset(self, name: str, branch_patterns: list[str]) -> int: ...
    def get_ruleset(self, ruleset_id: int) -> dict[str, Any]: ...
    def delete_ruleset(self, ruleset_id: int) -> None: ...
    def list_rulesets(self) -> list[dict[str, Any]]: ...
    def create_protection_ruleset(self, name: str, branch: str) -> int: ...
    def list_mq_branches(self) -> list[str]: ...
    def delete_branch(self, ref: str) -> None: ...
    def get_branch_sha(self, branch: str) -> str: ...
    def get_default_branch(self) -> str: ...
    def dispatch_ci(self, branch: str) -> None: ...
    def poll_ci(self, branch: str, timeout_seconds: int) -> bool: ...
    def poll_ci_with_url(
        self, branch: str, timeout_seconds: int
    ) -> tuple[bool, str]: ...
    def update_ref(self, ref: str, sha: str) -> None: ...
    def update_pr_base(self, pr_number: int, base: str) -> None: ...
    def compare_commits(self, base: str, head: str) -> str: ...
    def get_pr(self, pr_number: int) -> dict[str, Any]: ...
    def get_file_content(self, path: str, ref: str) -> dict[str, Any]: ...
    def put_file_content(
        self,
        path: str,
        branch: str,
        content_b64: str,
        message: str,
        sha: str | None = None,
    ) -> dict[str, Any]: ...
    def commit_files(self, branch: str, files: dict[str, str], message: str) -> str: ...
    def create_orphan_branch(self, branch: str, files: dict[str, str]) -> None: ...
    def get_pr_ci_status(self, pr_number: int) -> tuple[bool | None, str]: ...
    def dispatch_ci_on_ref(self, ref: str) -> None: ...
    def create_commit_status(
        self,
        sha: str,
        state: str,
        description: str = "",
        context: str = "Final Results",
    ) -> None: ...
    def get_user_permission(self, username: str) -> str: ...
    def get_pr_files(self, pr_number: int) -> list[str]: ...
    def get_pr_reviews(self, pr_number: int) -> list[dict]: ...
    def create_deployment(self, description: str, ref: str = "main") -> int: ...
    def update_deployment_status(
        self, deployment_id: int, state: str, description: str = ""
    ) -> None: ...
    def reset_call_counter(self) -> int: ...
    @property
    def rate_limit(self) -> RateLimitInfo: ...
